services:
  - type: web
    name: gigcredit-backend
    env: docker
    plan: free
    rootDir: backend
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: DB_NAME
        value: gigcredit
      - key: GROQ_API_KEY
        sync: false
      - key: HMAC_SECRET
        value: gigcredit-secure-hmac-secret
      - key: SERVER_API_KEY
        value: gigcredit-api-key
      - key: ENABLE_HMAC
        value: "false"
      - key: SKIP_AUTH
        value: "true"
